### ISSUE TITLE
add cxxfilt as dependency

### ISSUE THREAD

**Issue by teto** [gjcarneiro/pybindgen#16]
Hi,
With the latest PR it might be worth adding to setup.py a mention to cxxfilt as a mandatory or optional dependency (I am not sure which it is, it is certainly necessary for ns3 bindings)

**Comment by gjcarneiro** [comment]
It should be optional, since castxml is also optional.  cxxfilt is only needed for scanning, not for code generation.

**Comment by teto** [comment]
ok thanks
