### ISSUE TITLE
castxmlparser.py type_traits_classes.is_convertible() and Python 3

### ISSUE THREAD

**Issue by tomhenderson** [gjcarneiro/pybindgen#19]
In scanning ns-3 APIs with Python 3, everything nearly works but for a failure on one method in castxmlparser.py.

If I make this change to the file:

```
--- a/pybindgen/castxmlparser.py
+++ b/pybindgen/castxmlparser.py
@@ -1754,8 +1754,12 @@ pybindgen.settings.error_handler = ErrorHandler()
                 #print >> sys.stderr, "(lookup %r: %r)" % (name, class_wrapper)
                 return class_wrapper
 
-            if not type_traits_classes.is_convertible(cls, argument_types[0]):
-                return
+            try:
+                if not type_traits_classes.is_convertible(cls, argument_types[0]):
+                    return
+            except TypeError as e:
+                 print("Ignoring exception: %s %s %s" % (e, cls, argument_types[0]))
+                 return
```
and scan ns-3, I will obtain debugging prints on the following operators and classes:

```
Ignoring exception: '<' not supported between instances of 'NoneType' and 'NoneType' ns3::DoubleValue [class] ns3::DoubleValue [class]
Ignoring exception: '<' not supported between instances of 'NoneType' and 'NoneType' ns3::IntegerValue [class] ns3::IntegerValue [class]
...
```

i.e. all of the ns-3 'Value' classes throw an exception on this statement in Python 3, while they do not in Python 2.

We could work around by ignoring the exception such as above but am wondering about a more direct solution either in pybindgen/castxmlparser.py or in ns-3 custom bindings code.  We are moving to only support Python 3 in ns-3 going forward so a backward-compatible solution isn't needed.

Steps to reproduce the failure:
1) create and enter a Python3 venv
2) clone bake and configure ns-3-allinone target with some substitute repositories and ensure that scanning is enabled
3) try to rescan

```
export PATH=$PATH:`pwd`/build/bin
export PYTHONPATH=$PYTHONPATH:`pwd`/build/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/build/lib
./bake.py configure -e ns-3-allinone
./bake.py download
# replace pybindgen directory with latest pybindgen git tip on master branch
# replace ns-3-dev with the 'python3' branch of https://gitlab.com/tomhenderson/ns-3-dev.git 
./bake.py build
cd source/ns-3-dev
./waf configure
./waf --apiscan=core
```

**Comment by tomhenderson** [comment]
Ankit and I traced this to a Python 3 issue in pygccxml; we will try to solve it there and if so, close this issue.

**Comment by gjcarneiro** [comment]
I suspected as much, but wanted to try for myself and didn't find time.

**Comment by teto** [comment]
slighltly unrelated but when packaging ns-3.30, I get this failure: 
`pybindgen (found '0.19.0'), (need '0.19.0.post4+ng82c5fd2')`
Would be nice to have a new release ? it makes things easier when packaging otherwise I need to justify myself why I am going to package an unstable build (ie., 0.19.0.post4+ng82c5fd2).

**Comment by tomhenderson** [comment]
Closing (upstream pygccxml issue)
