### ISSUE TITLE
Release a new version on pypi

### ISSUE THREAD

**Issue by link2xt** [gjcarneiro/pybindgen#23]
https://pypi.org/project/PyBindGen/ has 0.20.0 now, which does not support python 3 and is not supported by the latest ns-3-dev.

I need a new version to make https://gitlab.com/nsnam/ns-3-dev/merge_requests/88 work without building pybindgen from git.

**Comment by gjcarneiro** [comment]
There is just _one_ commit after 0.20.0: https://github.com/gjcarneiro/pybindgen/commit/8ff989232cb48bfc0baea9fe9ebf1741d0a941cd

This has nothing to do with Python 3.

Surely ns-3-dev has a tool that downloads pybindgen from git for you?...

I'll consider it.  But I don't want to go down the path of making a new release for every PBG commit.

cc @tomhenderson

**Comment by link2xt** [comment]
Nevertheless, ns-3-dev requires it:
https://gitlab.com/nsnam/ns-3-dev/commit/cac2d1926301f792c4ac3ed98eed5ccae2e41152

**Comment by link2xt** [comment]
> I'll consider it. But I don't want to go down the path of making a new release for every PBG commit.

Something like 0.20.1 is justified IMO if it is a hotfix that is critical to ns-3-dev.

**Comment by tomhenderson** [comment]
I can confirm that ns-3-dev requires 8ff9892, but 0.20.0 supports Python 3 adequately at least for ns-3 purposes, and supports ns-3.30.

If I understand correctly, you are suggesting that we should no longer move pybindgen version forward in ns-3-dev without pybindgen releases, to support nix shell dev environment for rescanning bindings.

**Comment by gjcarneiro** [comment]
Ok, fine, I pushed 0.20.1.

**Comment by link2xt** [comment]
Thanks.

@tomhenderson > If I understand correctly, you are suggesting that we should no longer move pybindgen version forward in ns-3-dev without pybindgen releases, to support nix shell dev environment for rescanning bindings.

It is actually possible to build from git, though not supported officially. But I think minimal required version should not be moved if the fix is not critical.

**Comment by tomhenderson** [comment]
@link2txt I think we can try avoiding such non-release moves; it is usually the case that pybindgen version doesn't need to be moved that often for us; 8ff9892 was somewhat of an exception.
