### ISSUE TITLE
./waf shows version.py file not found

### ISSUE THREAD

**Issue by Lucky9128** [gjcarneiro/pybindgen#31]
this is the output of ./waf coomand
Waf: Entering directory `/home/lucky/ns-allinone-3.29/pybindgen/build'
Waf: Leaving directory `/home/lucky/ns-allinone-3.29/pybindgen/build'
source not found: 'version.py' in bld(source=[/home/lucky/ns-allinone-3.29/pybindgen/pybindgen/__init__.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/castxmlparser.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/container.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/converter_functions.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppattribute.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppclass.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppclass_container.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppcustomattribute.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppexception.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/cppmethod.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/enum.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/function.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/gccxmlparser.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/module.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/overloading.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/pytypeobject.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/settings.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/utils.py, /home/lucky/ns-allinone-3.29/pybindgen/pybindgen/wrapper_registry.py, 'version.py'], target='', meths=['process_rule', 'process_source'], features=[], path=/home/lucky/ns-allinone-3.29/pybindgen/pybindgen, idx=1, tg_idx_count=1, install_path='${PYTHONDIR}/pybindgen', prio=50, posted=True) in /home/lucky/ns-allinone-3.29/pybindgen/pybindgen

**Comment by gjcarneiro** [comment]
Just run `python setup.py`, so that `setuptools_scm` will generate this file automatically.

**Comment by gjcarneiro** [comment]
now `./waf configure` will do this for you
