### ISSUE TITLE
pygccxml submodule issues

### ISSUE THREAD

**Issue by chriscamacho** [gjcarneiro/pybindgen#36]
The docs state that pygccxml doesn't work with python3 which isn't the case (at least now!)

however current version of pybindgen doesn't seem to work with it.

this is what happens when I run the last code fragment in the tutorial

```
./gen-make-binding.py dunno
Traceback (most recent call last):
  File "./gen-make-binding.py", line 14, in <module>
    my_module_gen()
  File "./gen-make-binding.py", line 11, in my_module_gen
    module_parser.parse([sys.argv[1]], includes=['"../raylib/src/raylib.h"'], pygen_sink=FileCodeSink(sys.stdout))
  File "/home/chris/.local/lib/python3.8/site-packages/pybindgen/gccxmlparser.py", line 598, in parse
    self.parse_init(header_files, include_paths, whitelist_paths, includes, pygen_sink,
  File "/home/chris/.local/lib/python3.8/site-packages/pybindgen/gccxmlparser.py", line 694, in parse_init
    self.gccxml_config = parser.gccxml_configuration_t(**gccxml_options)
AttributeError: module 'pygccxml.parser' has no attribute 'gccxml_configuration_t'
```

**Comment by gjcarneiro** [comment]
gccxmlparser has been replaced with castxmlparser (as the GCC-XML project is unmaintained and CastXML is slightly more maintained).

**Comment by chriscamacho** [comment]
can't honestly remember what I was trying to do with this, has the tutorial for phbindgen been updated to reflect how it should be used with python 3 ?

**Comment by gjcarneiro** [comment]
Well, yes, and no.  The docs were updated, in git, but it seems that in readthedocs it hasn't updated yet.
