### ISSUE TITLE
Deprecation warnings for PyEval_ThreadsInitialized()

### ISSUE THREAD

**Issue by tomhenderson** [gjcarneiro/pybindgen#40]
On ns-3 (downstream) we are seeing build failures on Python 3.9 due to these deprecation warnings.  I read through issue #37 suggesting needing to call PyEval_InitThreads only for Python <3.7, and perhaps similarly, these PyEval_ThreadsInitialized() methods should be enabled only for the older Python versions.

**Comment by gri6507** [comment]
One way to fix this would be to wrap the call to `PyEval_InitThreads` with `#if PY_VERSION_HEX < 0x03070000`

**Comment by gjcarneiro** [comment]
I don't understand.  `PyEval_InitThreads` is not part of pybindgen generated code, as far as I can tell.

**Comment by tomhenderson** [comment]
I agree that `PyEval_InitThreads` is not an issue here, but there is an issue with `typehandlers/base.py` including`PyEval_ThreadsInitialized()`.

I have fixed the issues in the ns-3 code (would appreciate a review if you have time: https://gitlab.com/nsnam/ns-3-dev/-/merge_requests/503) but the code in `typehandlers/base.py` leads to additional calls to `PyEval_ThreadsInitialized()` that need to be avoided.  I can put similar guards on checking sys.hexversion in `typehandlers/base.py` if you agree with the approach.

**Comment by gjcarneiro** [comment]
I see.  Fixed in master.
